AGES = [str(age) for age in range(18, 36)]
MAX_DATES = [str(count) for count in range(3, 13)]
INTERESTS = [
    "Outdoor/Adventure",
    "Sports",
    "Cooking/Baking",
    "Intellectual Pursuits",
    "Travel",
    "Reading",
    "Art",
    "Dancing",
    "Movies/TV",
    "Volunteering/Service",
    "Fitness",
    "Nature/Gardening",
    "Creative Pursuits",
    "Games",
    "Music",
]

SUMMER_2026_SIGNUP_FORM = {
    "id": "little-dates-club-summer-2026",
    "title": "Little Dates Club Summer 2026 Sign-Up",
    "session_label": "Summer 2026",
    "source": "Google Form printout imported 2026-05-12",
    "audience": "participant_intake",
    "managed_by": "organizers",
    "deadline": "2026-05-22",
    "program_dates": {"starts_on": "2026-06-03", "ends_on": "2026-08-14"},
    "donation": {
        "suggested_amount": 25,
        "zelle": "littledatesclub@gmail.com",
        "venmo": "@littledatesclub",
    },
    "capacity_notice": {
        "men": "Spots for the men are full; new male sign-ups should be waitlisted.",
        "women": "Open spots remain for ladies.",
    },
    "orientation": {
        "location": "Radich Home, Rockville, MD",
        "required_for": "new_participants",
        "women": ["2026-05-17 14:00-16:00", "2026-05-23 10:00-12:00"],
        "men": ["2026-05-17 19:00-21:00", "2026-05-23 14:00-16:00"],
    },
    "eligibility_requirements": [
        "Participant is not already in an exclusive relationship.",
        "Participant will commit to assigned dates up to their selected maximum.",
        "Assigned dates must be completed between June 3 and August 14.",
        "New participants must attend mandatory in-person orientation.",
    ],
    "fields": [
        {
            "key": "first_name",
            "number": 1,
            "label": "FIRST Name",
            "type": "short_text",
            "required": True,
            "maps_to": "participant.first_name",
        },
        {
            "key": "last_name",
            "number": 2,
            "label": "LAST Name",
            "type": "short_text",
            "required": True,
            "maps_to": "participant.last_name",
        },
        {
            "key": "phone",
            "number": 3,
            "label": "PHONE Number",
            "type": "phone",
            "required": True,
            "maps_to": "participant.phone",
        },
        {
            "key": "email",
            "number": 4,
            "label": "EMAIL",
            "help_text": "Use the email checked most often; this is used for all LDC correspondence.",
            "type": "email",
            "required": True,
            "maps_to": "participant.email",
        },
        {
            "key": "gender",
            "number": 5,
            "label": "MALE/FEMALE",
            "type": "radio",
            "required": True,
            "options": ["Male", "Female"],
            "maps_to": "participant.gender",
        },
        {
            "key": "age",
            "number": 6,
            "label": "AGE",
            "help_text": "Your age.",
            "type": "dropdown",
            "required": True,
            "options": AGES,
            "maps_to": "participant.flexible_fields.age_at_signup",
        },
        {
            "key": "age_range",
            "number": 7,
            "label": "RANGE",
            "help_text": "What ages are you interested in dating? The more ages checked, the more potential dates are available.",
            "type": "checkboxes",
            "required": True,
            "options": AGES,
            "maps_to": "participant.age_range_min_max",
        },
        {
            "key": "max_dates",
            "number": 8,
            "label": "MAX DATES",
            "help_text": "Maximum number of little dates requested for the ten-week session.",
            "type": "radio",
            "required": True,
            "options": MAX_DATES,
            "maps_to": "participant.desired_dates_per_session",
        },
        {
            "key": "city_state",
            "number": 9,
            "label": "CITY AND STATE",
            "help_text": "Home city/state, plus an optional second city/state for work or other date-planning locations.",
            "type": "long_text",
            "required": True,
            "maps_to": "participant.city_state_raw",
        },
        {
            "key": "interests",
            "number": 10,
            "label": "INTERESTS",
            "help_text": "Interests and hobbies outside work or school.",
            "type": "checkboxes",
            "required": False,
            "options": INTERESTS,
            "maps_to": "participant.interests",
        },
        {
            "key": "referral_source",
            "number": 11,
            "label": "How did you hear about this club?",
            "type": "short_text",
            "required": True,
            "maps_to": "participant.flexible_fields.referral_source",
        },
        {
            "key": "date_commitment_ack",
            "number": 12,
            "label": "Date and orientation commitment",
            "type": "radio",
            "required": True,
            "options": ["Yes"],
            "maps_to": "registration.flexible_fields.date_commitment_ack",
        },
        {
            "key": "location_ack",
            "number": 13,
            "label": "Date location acknowledgement",
            "type": "radio",
            "required": True,
            "options": ["Yes"],
            "maps_to": "registration.flexible_fields.location_ack",
        },
        {
            "key": "code_of_conduct_ack",
            "number": 14,
            "label": "Code of Conduct Statement",
            "type": "statement_checkbox",
            "required": True,
            "options": ["Yes, I have read and agree with the Code of Conduct Statement"],
            "maps_to": "registration.flexible_fields.code_of_conduct_ack",
        },
        {
            "key": "safety_ack",
            "number": 15,
            "label": "Safety Statement",
            "type": "statement_checkbox",
            "required": True,
            "options": ["Yes, I have read and agree with the Safety Statement"],
            "maps_to": "registration.signed_safety_statement",
        },
        {
            "key": "liability_ack",
            "number": 16,
            "label": "Liability Statement",
            "type": "statement_checkbox",
            "required": True,
            "options": ["Yes, I have read and agree with the Liability Statement"],
            "maps_to": "registration.signed_liability_statement",
        },
        {
            "key": "previous_dates",
            "number": 17,
            "label": "Previous LDC dates",
            "help_text": 'If new to the club, enter "new to the club."',
            "type": "long_text",
            "required": True,
            "maps_to": "registration.flexible_fields.previous_dates_raw",
        },
        {
            "key": "cannot_date",
            "number": 18,
            "label": "Unable to date",
            "help_text": "People the participant is unable to date because of family connection, past dating history, or other reasons.",
            "type": "long_text",
            "required": False,
            "maps_to": "participant.cannot_date_raw",
        },
        {
            "key": "vision_statement",
            "number": 19,
            "label": "VISION",
            "help_text": "Organizer-only vision for relationships and marriage, including children, faith, work, and related areas.",
            "type": "long_text",
            "required": False,
            "private": True,
            "maps_to": "participant.vision_statement",
        },
    ],
}


def get_summer_2026_signup_form() -> dict:
    return SUMMER_2026_SIGNUP_FORM
